ARCH=sm83
MACHINE=
SCRIPT_NAME=sm83
#OUTPUT_ARCH="sm83"
OUTPUT_FORMAT="elf32-sm83"
MAXPAGESIZE=1
EMBEDDED=yes
TEMPLATE_NAME=elf

TEXT_START_ADDR=0x100
#TEXT_LENGTH=0
#DATA_ORIGIN=0
#DATA_LENGTH=0
EXTRA_EM_FILE=sm83

#FUSE_NAME=fuse

#EEPROM_LENGTH=64K
#FUSE_LENGTH=1K
#LOCK_LENGTH=1K
#SIGNATURE_LENGTH=1K
#USER_SIGNATURE_LENGTH=1K
